import Head from 'next/head'
import Image from 'next/image'
import clientPromise from '../../lib/mongodb'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navigation from '../../components/Navigation'
import ProductCard from '../../components/ProductCard'

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps(context) {
  const client = await clientPromise
  const db = client.db('hot_wheels')
  let cars = await db.collection('cars').find({}).toArray()
  cars = JSON.parse(JSON.stringify(cars))
  return {
    props: { cars },
  }
}

export default function Home({ cars }) {
  return (
    <>
      <Head>
        <title>Create App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main className={styles.main}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/fl-logo-dark.png"
            alt="Flying Lugnut Logo"
            width={200}
            height={180}
            priority
          />
        </div>
        <div className={styles.grid}>
        {cars.map(car => (
                    <ProductCard
                        key={car.id}
                        car={car}
                        productTitle={ car.make + ' ' + car.model }
                        productSubtitle={ car.trim }
                        productImage={ car.mainImage }
                        productView={ `/product?id=${car._id}` }
                    />
                ))}
        </div>
      </main>
    </>
  )
}
